function handles = get_default_values(handles)
%GET_DEFAULT_VALUES    lädt Standardeinstellungen für ACCESS_TOOL
%    HANDLES = GET_DEFAULT_VALUES(HANDLES) fügt der HANDLES-Struktur Standardwerte 
%    hinzu.

% Standardbezeichnungen:
handles.System.seasons =   {... % Typen der Jahreszeiten
	'Summer', 'Sommer';... 
	'Transi', 'Übergangszeit';...
	'Winter', 'Winter';...
	}; 
handles.System.weekdays =  {... % Typen der Wochentage
	'Workda', 'Werktag';...
	'Saturd', 'Samstag';...
	'Sunday', 'Sonntag';...
	};  
handles.System.housholds = {... % Definition der Haushaltskategorien:
	'sing_vt', 'Single Vollzeit';...
	'coup_vt', 'Paar Vollzeit';...
	'sing_pt', 'Single Teilzeit';...
	'coup_pt', 'Paar Teilzeit';...
	'sing_rt', 'Single Pension';...
	'coup_rt', 'Paar Pension';...
	'fami_2v', 'Familie, 2 Mitglieder Vollzeit';...
	'fami_1v', 'Familie, 1 Mitglied Vollzeit';...
	'fami_rt', 'Familie mit Pensionist(en)';...
	};

% die weiteren Daten der Haushalte einlesen:
handles.Households = load_household_parameter();

% Definition der verschiedenen "Worst Cases":
handles.System.wc_households = {...
	'Kein';...
	'Höchster Energieverbrauch';...
	'Niedrigster Energieverbrauch';...
	'Höchste Leistungsaufnahme';...
	};
handles.Settings.Worstcase_Housholds = 1;
handles.System.wc_generation = {...
	'Kein';...
	'Höchste Tageseinspeisung';...
	'Niedrigste Tageseinspeisung';...
	'Höchste Leistung';...
	};
handles.Settings.Worstcase_Generation = 1;
% Anzahl an maximal möglichen verschiedenen Erzeugungsanlagen im GUI:
handles.Settings.Number_Generation_Max = 15;

% Default-Definition der Anlagenarten
handles.System.Sola.Typs = {...
	'Keine Anlage ausgewählt','';...
	'Fix, 90° - 0°','fix_30°_0°';...
	'Fix, 30° - 0°','fix_90°_0°';...
	'Tracker','trac';...
	};
handles.System.Wind.Typs = {...
	'Keine Anlage ausgewählt','';...
	'Windkraftanlage 1','wind_1';...
	'Windkraftanlage 2','wind_2';...
	'Windkraftanlage 3','wind_3';...
	};

% Für dynamische Tags der einzelnen Einstellungsmöglichkeiten, deren grobe
% Struktur definieren:
handles.System.Sola.Tags = {...
	'popup_genera_pv_','_typ';...
	'edit_genera_pv_','_number';...
	'edit_genera_pv_','_installed_power'; ...
	'push_genera_pv_','_parameters';...
	'text_genera_pv_','_unit';...
	};
handles.System.Wind.Tags = {...
	'popup_genera_wind_','_typ';...
	'edit_genera_wind_','_number';...
	'edit_genera_wind_','_installed_power';...
	'push_genera_wind_','_parameters';...
	'text_genera_wind_','_unit';...
	};
% Angabe der Höhe eines Eingabefeldes in Pixel:
handles.System.Generation.Input_Field_Height = 27;

%Default Werte einstellen (alle Anlagen aus):
Default_Plant.Typ = 1;
Default_Plant.Number = 0;
Default_Plant.Power_Installed = 0;
handles.System.Sola.Default_Plant = Default_Plant;
handles.System.Wind.Default_Plant = Default_Plant;

handles.Settings.Sola.Plant_1 = Default_Plant;
handles.Settings.Sola.Plant_2 = Default_Plant;

handles.Settings.Wind.Plant_1 = Default_Plant;
handles.Settings.Wind.Plant_2 = Default_Plant;

% Dateiasugabetypen:
handles.System.outputdata_types = {...
	'*.mat','.mat - MATLAB Binärdatei';...
	'*.csv','.csv - Commaseparated Values';...
	'*.xlsx','.xlsx - EXCEL Spreadsheet';...
	};
handles.Settings.Output_Datatyp = 1;

% Zeitauflösungen:
handles.System.time_resolutions = {...
	'sec - Sekunden',     1;...
	'min - Minuten',     60;...
	'5mi - 5 Minuten',  300;...
	'quh - 15 Minuten', 900;...
	};
handles.Settings.Time_Resolution = 1;

% Anzahl an verschiedenen Datensätzen, die erzeugt werden sollen:
handles.Settings.Several_Datasets_Number = 1;
handles.Settings.Create_Several_Datasets = 0;

% Anzahl der Haushalte Null setzen:
for i=1:size(handles.System.housholds,1)
	handles.Settings.Households.(handles.System.housholds{i,1}).Number = 0;
end

% Jahreszeiten setzen:
handles.Settings.Season = logical([1 0 0]');
handles.Settings.Weekday = logical([1 0 0]');

% Standard-Dateipfade für Testzwecke:
handles.Settings.Database.Path = handles.Settings.Main_Path;
handles.Settings.Database.Name = 'Test_Datenbank';

handles.Settings.Last_Conf.Path = handles.Settings.Main_Path;
handles.Settings.Last_Conf.Name = 'Einstellungen';
handles.Settings.Last_Conf.Exte = '.conf';

handles.Settings.Target.Path = [handles.Settings.Main_Path,'Ergebnisse'];
handles.Settings.Target.Name = 'Datenbankauszug';
handles.Settings.Target.Exte = '.mat';
end