function handles = get_default_values(handles)
%GET_DEFAULT_VALUES    laden der Default-Werte für Simulationsprogramm
%    HANDLES = GET_DEFAULT_VALUES(HANDLES) fügt der HANDLES-Struktur des GUI
%    'Simulation' alle wichtigen Default-Werte und Definitionen hinzu. Falls
%    keine anderen Programmeinstellungen (z.B. von einem früheren
%    Simultionsdurchlauf) vorhanden sind, werden diese Werte herangezogen.

%    Franz Zeilinger - 03.08.2011

%===============================================================================
%                  D E F A U L T - D E F I N I T I O N E N
%===============================================================================
%
%-------------------------------------------------------------------------------
% Einstellungen zur Programmkonfiguration (Datei-Verwaltung, Optionen):
%-------------------------------------------------------------------------------
% Speicherort für erzeugte Daten / Konfigurationseinstellungen:
Save = handles.Configuration.Save;
Save.Settings.Name = 'Einstellungen';
Save.Settings.Ext = '.conf';
% Ergebnisse und zusätzliche Daten werden im übergeordneten Verzeichnis
% abgelegt. Dieses muss zuvor ermittelt werden:
ind = strfind(Save.Settings.Path,'\');
Save.Additional_Data.Path = Save.Settings.Path(1:ind(end-1));
Save.Data.Main_Path = [Save.Additional_Data.Path,'Simulationsergebnisse\'];
% Default-Parameterwerte sollten hier abgelegt sein:
Save.Source.Path = Save.Settings.Path;
Save.Source.Parameter_Name = 'Default_Parameterwerte';
% Parameter für Joblistendatei (Multiple Simulationen):
Save.Joblist.Path = Save.Additional_Data.Path;
Save.Joblist.Parameter_Name = Save.Source.Parameter_Name;
Save.Joblist.List_Name = 'Simulationsreihe';
Save.Frequency.Path = Save.Additional_Data.Path;
Save.Frequency.Name = 'Frequenzdaten';
Save.Frequency.Extension = '.fqd';

opt.show_data = 1; %Daten nach Simulation anzeigen
opt.savas_xls = 0; %Daten als .xls nach Sim. speichern
opt.savas_csv = 0; %Daten als .xls nach Sim. speichern
opt.use_last_frequency_data = 0; %Aktuelle Frequenzdaten heranziehen
opt.use_different_frequency_data = 0; % Verwendung von verschiedenen Frequenzdaten
opt.use_same_paramter_file = 0;
opt.multiple_simulation = 0; %Modus auf Einzelsimualtion
opt.simsettings_load_from_paramfile = 0;   %Daten von Parameterdatei laden
opt.simsettings_load_from_main_window = 1; %Einstellungen von Hauptfenster
opt.use_same_devices = 0; %Wenn möglich, gleiche Geräteinstanzen verwenden
opt.use_same_dsm = 0; % Wenn möglich, gleiche DSM-Instanzen verwenden
opt.compute_parallel = 0; % Parallelrechnen per default aus.

Configuration.Save = Save;
Configuration.Options = opt; 
handles.Configuration = Configuration;

%===============================================================================
%               P A R A M E T E R D E F I N I T I O N E N :
%===============================================================================
%
%-------------------------------------------------------------------------------
% Möglichkeiten für alle zu simulierenden Geräte: Cell-Array für  
% automatisches abarbeiten:
%     { Variablenname, ausgeschriebener Name, Handle auf zuständige Klasse}
%-------------------------------------------------------------------------------
Model.Devices_Pool = {...
	'refrig', 'Kühlschränke',         @Thermal_Storage;...
% 	'refr_1', 'Kühlschränke 1',       @Thermal_Storage;...
	'pc_des', 'Desktop PCs',          @Probable_Operation;...
	'pc_not', 'Notebooks',            @Probable_Operation;...
	'mon_pc', 'Monitore (PCs)',       @Probable_Operation;...
	'pr_las', 'Laserdrucker',         @Interrupted_Operation;...
	'pr_ink', 'Tintenstrahldrucker',  @Probable_Operation;...
	'offdiv', 'Diverse Bürogeräte',   @Probable_Operation;...
	'tv_set', 'Fernseher',            @Probable_Operation;...
	'set_to', 'Set-Top-Boxen',        @Probable_Operation;...
	'vid_eq', 'Video-Equipment',      @Probable_Operation;...
	'gam_co', 'Game-Konsolen',        @Probable_Operation;...
	'hi_fi_', 'Hi-Fi-Geräte',         @Probable_Operation;...
	'radio_', 'Radios',               @Probable_Operation;...
	'illumi', 'Beleuchtung',          @Interrupted_Operation;...
	'illum1', 'Beleuchtung 1',        @Interrupted_Operation;...
	'illum2', 'Beleuchtung 2',        @Interrupted_Operation;...
	'illum3', 'Beleuchtung 3',        @Interrupted_Operation;...
	'illum4', 'Beleuchtung 4',        @Interrupted_Operation;...
	'illum5', 'Beleuchtung 5',        @Interrupted_Operation;...
	'illum6', 'Beleuchtung 6',        @Interrupted_Operation;...
	'washer', 'Waschmaschinen',       @Loadcurve_Operation;...
% 	'wash_1', 'Waschmaschinen 1',     @Loadcurve_Operation;...
% 	'wash_2', 'Waschmaschinen 2',     @Loadcurve_Operation;...
% 	'wash_3', 'Waschmaschinen 3',     @Loadcurve_Operation;...
% 	'wash_4', 'Waschmaschinen 4',     @Loadcurve_Operation;...
% 	'wash_5', 'Waschmaschinen 5',     @Loadcurve_Operation;...
% 	'wash_6', 'Waschmaschinen 6',     @Loadcurve_Operation;...
	'dishwa', 'Geschirrspüler',       @Loadcurve_Operation;...
% 	'dish_1', 'Geschirrspüler 1',     @Loadcurve_Operation;...
% 	'dish_2', 'Geschirrspüler 2',     @Loadcurve_Operation;...
% 	'dish_3', 'Geschirrspüler 3',     @Loadcurve_Operation;...
% 	'dish_4', 'Geschirrspüler 4',     @Loadcurve_Operation;...
	'cl_dry', 'Wäschetrockner',       @Loadcurve_Operation;...
% 	'cl_dr1', 'Wäschetrockner 1',     @Loadcurve_Operation;...
% 	'cl_dr2', 'Wäschetrockner 2',     @Loadcurve_Operation;...
% 	'cl_dr3', 'Wäschetrockner 3',     @Loadcurve_Operation;...
% 	'cl_dr4', 'Wäschetrockner 4',     @Loadcurve_Operation;...
% 	'cl_dr5', 'Wäschetrockner 5',     @Loadcurve_Operation;...
% 	'cl_dr6', 'Wäschetrockner 6',     @Loadcurve_Operation;...
	'cir_pu', 'Umwälzpumpen',         @Probable_Operation;...
% 	'cir_p1', 'Umwälzpumpen 1',       @Probable_Operation;...
% 	'cir_p2', 'Umwälzpumpen 2',       @Probable_Operation;...
% 	'cir_p3', 'Umwälzpumpen 3',       @Probable_Operation;...
% 	'cir_p4', 'Umwälzpumpen 4',       @Probable_Operation;...
% 	'cir_p5', 'Umwälzpumpen 5',       @Probable_Operation;...
% 	'cir_p6', 'Umwälzpumpen 6',       @Probable_Operation;...
	'div_de', 'Diverse Geräte',       @Probable_Operation;...
	'div_d1', 'Diverse Geräte 1',     @Probable_Operation;...
	'div_d2', 'Diverse Geräte 2',     @Probable_Operation;...
	'div_d3', 'Diverse Geräte 3',     @Probable_Operation;...
	'div_d4', 'Diverse Geräte 4',     @Probable_Operation;...
	'div_d5', 'Diverse Geräte 5',     @Interrupted_Operation;...
	'stove_', 'Herd',                 @Interrupted_Operation;...
    'oven__', 'Backrohr',             @Probable_Operation;...
	'microw', 'Mikrowelle',           @Interrupted_Operation;...
	'ki_mis', 'Diverse Küchenger.',   @Interrupted_Operation;...
	'ki_mi1', 'Diverse Küchenger. 1', @Interrupted_Operation;...
	'ki_mi2', 'Diverse Küchenger. 2', @Interrupted_Operation;...
	'ki_mi3', 'Diverse Küchenger. 3', @Interrupted_Operation;...
	'freeze', 'Gefriergeräte',        @Thermal_Storage;...
% 	'frez_1', 'Gefriergeräte 1',      @Thermal_Storage;...
	'wa_hea', 'Durchlauferhitzer',    @Interrupted_Operation;...
% 	'wa_he1', 'Durchlauferhitzer 1',  @Interrupted_Operation;...
% 	'wa_he2', 'Durchlauferhitzer 2',  @Interrupted_Operation;...
	'wa_boi', 'Warmwasserboiler',     @Interrupted_Operation;...
% 	'wa_bo1', 'Warmwasserboiler 1',   @Interrupted_Operation;...
% 	'wa_bo2', 'Warmwasserboiler 2',   @Interrupted_Operation;...
	'hea_ra', 'Heizkörper',           @Interrupted_Operation;...
% 	'hea_r1', 'Heizkörper 1',         @Interrupted_Operation;...
% 	'hea_r2', 'Heizkörper 2',         @Interrupted_Operation;...
	'hea_wp', 'Wärmepumpe',           @Probable_Operation;...
% 	'hea_w1', 'Wärmepumpe 1',         @Probable_Operation;...
% 	'hea_w2', 'Wärmepumpe 2',         @Probable_Operation;...
	}; 

%-------------------------------------------------------------------------------
% Mögliche Gerätegruppen:
%     { Variablenname, ausgeschriebener Name }
%-------------------------------------------------------------------------------
Model.Device_Groups_Pool = {...
	'gr_avd', 'Gruppe "Audio-Video-Geräte"';...
	'gr_ill', 'Gruppe "Beleuchtung"';...
	'gr_off', 'Gruppe "Bürogeräte"';...
	'gr_hea', 'Gruppe "Heizung"';...
	'gr_kit', 'Gruppe "Küche"';...
	'gr_hwa', 'Gruppe "Warmwasser"';...
	'gr_mis', 'Gruppe "Diverses"';...
% 	'gr_dis', 'Gruppe "Geschirrspüler"';...
    'gr_col', 'Gruppe "Kühlgeräte"';...
% 	'gr_was', 'Gruppe "Waschmaschinen"';...
% 	'gr_cld', 'Gruppe "Wäschetrockner"';...
% 	'gr_cir', 'Gruppe "Umwälzpumpen"';...
	};

%-------------------------------------------------------------------------------
% Welche Geräte und Gerätegruppen sollen über das GUI angesprochen werden?
%     { Variablenname, ausgeschriebener Name }
% (ACHTUNG: die hier verwendeten Geräte bzw. Gruppen müssen in den beiden zuvor
% definierten Cell-Arrays (Devices_Pool und Device_Groups_Pool) vorkommen!) 
%-------------------------------------------------------------------------------
Model.Device_Assembly_Pool = {...
	'gr_avd', 'Gruppe "Audio-Video-Geräte"';
	'gr_ill', 'Gruppe "Beleuchtung"';...
	'gr_off', 'Gruppe "Bürogeräte"';...
	'gr_mis', 'Gruppe "Diverses"';...
	'gr_hea', 'Gruppe "Heizung"';...
	'gr_kit', 'Gruppe "Küche"';...
	'gr_hwa', 'Gruppe "Warmwasser"';...
    'gr_col', 'Gruppe "Kühlgeräte"';...
% 	'freeze', 'Gefriergeräte';...
% 	'refrig', 'Kühlschränke';...
	'dishwa', 'Geschirrspüler';...
% 	'gr_dis', 'Gruppe "Geschirrspüler"';...
	'cl_dry', 'Wäschetrockner';...
% 	'gr_cld', 'Gruppe "Wäschetrockner"';...
	'washer', 'Waschmaschinen';...
% 	'gr_was', 'Gruppe "Waschmaschinen"';...
	'cir_pu', 'Umwälzpumpen';... 
% 	'gr_cir', 'Gruppe "Umwälzpumpen"';...
	};

%-------------------------------------------------------------------------------
% ACHTUNG: folgende Listen definieren die möglichen Namen für die verschiedenen,
% in diesem Programm vorkommenden Parameter. Werden diese Namen hier geändert,
% müssen die korrespondieren Properties in den Geräteklassen (bzw. bei den
% Simulationsparametern in den Programmfunktionen) dementsprechend geändert
% werden! Diese Definitionen dienen dazu, zukünftige weitere Parameter einfach
% ins Programm einfügen zu können, da deren Behandlung für Einlesen und Ausgabe
% mit Hilfe der rw_Funktinen automatisiert abläuft.
% Für nähere Infos siehe Hilfetext der verwendeten rw_-Funktionen (zu
% finden im Ordner 'Hilfsfunktionen' im Programmverzeichnis)
%-------------------------------------------------------------------------------

% Auflistung aller möglichen Simulationsparameter:
%     {Parametername, Handle auf zuständige rw_-Funktion}
Model.Sim_Param_Pool = {...
	'Date_Start',     @rw_sim_parameter;...
	'Date_End',       @rw_sim_parameter;...
	'Sim_Resolution', @rw_sim_parameter;...
	'Number_User',    @rw_sim_parameter;
	'Use_DSM',        @rw_sim_parameter;...
	'Use_Same_DSM',   @rw_sim_parameter;...
	'Device_Assembly',@rw_dev_assembly;...
	};

f_val = '%6.1f'; %Formatstring für Parameterwerte
f_sig = '%4.1f'; %Formatstring für Varianzen u.d.gl.

% Auflistung möglicher Parametertypen der Geräte:
% {Parametername, ...
%      Handle auf zuständige rw_-Funktion,...
%      Argumtente f. rw_-Funtkion;}
% Nichtbnötigte Argumente werden (um Cell-Array zu ermöglichen) mit leeren
% Zellen ('[]') befüllt, damit jede Zeile die gleiche Spaltenanzahl hat!
Model.Parameter_Pool = {...
	'Power_Nominal',...          % Nennleistung
	    @rw_single_parameter,... 
	    'W',  '%',   f_val, f_sig, [],    [];...
	'Cos_Phi_Nominal',...        % Nennleistungsfaktor
		@rw_single_parameter,... 
	    '',   '%',   f_val, f_sig, [],    [];...
	'Power_Stand_by',...         % Stand-by-Verbrauch
	    @rw_single_parameter,... 
	    'W',  '%',   f_val, f_sig, [],    [];...
	'Cos_Phi_Stand_by',...        % Nennleistungsfaktor im Stand-by-Betrieb
		@rw_single_parameter,... 
	    '',   '%',   f_val, f_sig, [],    [];...
	'Three_Phase_Device',...      % Dreiphasiges Gerät? (1 = Ja)
		@rw_single_parameter,... 
	    '','n.n.',   f_val, f_sig, [],    [];...
	'Factor_Inrush',...          % Faktor Einschaltspitze
	    @rw_single_parameter,... 
	    '%',  '%',   f_val, f_sig, [],    [];...
	'Time_Inrush_Decay',...      % Abklingezeit Einschaltspitze
	    @rw_single_parameter,... 
	    's'  ,'%',   f_val, f_sig, [],    [];...
	'Dir_therm_Flow',...         % Richtung der thermischen Energiezufuhr
		@rw_single_parameter,... 
	    '','n.n.', '%5.0f', f_sig, [],    [];...
	'Efficency',...              % Wirkungsgrad
	    @rw_single_parameter,... 
	    '%',  '%',   f_val, f_sig, [],    [];...      
	'Switch_Point',...           % Schaltschwelle
	    @rw_single_parameter,... 
	    '°C', '%',   f_val, f_sig, [],    [];...      
	'Heat_Capacity',...          % Wärmekapazität 
	    @rw_single_parameter,... 
	    'J/K','%',   f_val, f_sig, [],    [];...      
	'Thermal_Res',...            % thermischer Widerstand
	    @rw_single_parameter,... 
	    'K/W','%',   f_val, f_sig, [],    [];...      
	'Temp_Set',...               % Solltemperatur
	    @rw_single_parameter,... 
	    '°C', '%',   f_val, f_sig, [],    [];...      
	'Temp_Ambiance',...          % Umgebungstemperatur
	    @rw_single_parameter,... 
	    '°C', '%',   f_val, f_sig, [],    [];...      
	'Operat_Sim_Start',...       % Wahrschl. für Betrieb bei Simulationsstart
	    @rw_single_parameter,... 
	    '%',  'n.n.',f_val, f_sig, [],    [];...      
	'Time_Period',...            % Periodendauer 
	    @rw_single_parameter,... 
	    'min','%',   f_val, f_sig, [],    [];...      
	'Time_typ_Run',...           % typ. Laufzeit
	    @rw_parameter_list,... 
	    'min','%',   f_val, f_sig,'%5.1f','%5.1f';... 
	'Time_Start',...             % Startzeit
	    @rw_parameter_list,... 
	    'Uhr','min', '%s',  f_sig, '%s' , '%5.1f';...
	'Start_Probability',...      % Einschaltwahrscheinlichkeit
	    @rw_parameter_list,... 
	    '%',  'n.n.',f_val, f_sig,'%5.1f','%5.1f';... 
	'Power_Loadcurve',...        % Lastkurve
	    @rw_loadcurve,...                 
	    [],   [],    [],    [],    [],    [];...    
	'Loadcurve_Allocation',...   % Einschaltwahrscheinlichkeit der versch. Lastkurven
	    @rw_parameter_list,...
	    '%',  'n.n.',f_val, f_sig,'%5.1f','%5.1f';... 
	'Loadcurve_non_stop_Parts',... % Definition der zusammenhängenden Teil der Lastk.
	    @rw_loadcurve_parts,...
	    [],   [],    [],    [],    [],    [];...
	'Device_Group_Members',...   % Mitglieder einer Gerätegruppe
	    @rw_device_group_members,...
	    [],   [],    [],    [],    [],    [];...
	'Time_Starts_per_Hour',...   % Anzahl der Starts pro Stunde
	    @rw_single_parameter,...
	    '1/h','%',   f_val, f_sig, [],    [];...
	'Time_run_Duty_Cycle',...    % typische Laufzeit innerhalb einer Periode
	    @rw_single_parameter,...
	    '%',  '%',   f_val, f_sig, [],    [];...	
	'Time_min_Run',...           % minimale Einschaltzeit eines Gerätes
	    @rw_single_parameter,...
	    'min','%',   f_val, f_sig, [],    [];...	
		};

% Auflistung möglicher Parametertype für DSM:
Model.DSM_Param_Pool = {...
	'DSM_Input_Mode',...       % Auswahl des zu verwendenden DSM-Algorithmus
	    @rw_dsm_modus,... 
	    [],    [],    [],     [],    [],    [];...      
	'Check_former_Frequ_Data',... % Überprüfung zurückliegender Frequenzdaten
	    @rw_single_parameter,... 
	    'bool','n.n.',[],     [],    [],    [];...      
	'DSM_Output_Mode',...      % Aúswahl der Reaktion des Gerätes
	    @rw_dsm_modus,... 
	    [],    [],    [],     [],    [],    [];...      
	'Frequency_Level',...      % Frequenzwert, ab dem DSM eingreift
	    @rw_single_parameter,... 
	    'Hz',  '%',   f_val,  f_sig, [],    [];...    
	'Frequency_Hysteresis',... % Frequenzwert der Breite der Hysterese der Frequenz 
	    @rw_single_parameter,... 
	    'Hz',  '%',   f_val,  f_sig, [],    [];...  
	'Frequ_Filter_Time',...    % Filterzeitkonstante für Frequenzfilterung
	    @rw_single_parameter,... 
	    'min', '%',   f_val,  f_sig, [],    [];...  	
	'Prioritys_Number',...     % Anzahl an Prioritätsgruppen von Verbrauchern
	    @rw_single_parameter,... 
	    '',    'n.n.','%6.0f',f_sig, [],    [];...      
	'Prioritys_Freq_Range',... % Frequenzbereich der einzelnen Prioritätsgruppen
	    @rw_parameter_list,... 
	    'Hz',  '%',   f_val,  f_sig,'%5.1f','%5.1f';... 
	'Prioritys_Allocation',... % Verteilung der Verbr. auf die Prioritätsgruppen
	    @rw_parameter_list,... 
	    '%',   'n.n.',f_val,  f_sig,'%5.1f','%5.1f';... 
	'Time_Delay_Restore_Op',...% Zeitverzögerung Wiederinbetriebnahme
	    @rw_single_parameter,... 
	    'min', '%',   f_val,  f_sig, [],    [];...  	
	'Temp_Set_Variation',...   % Höhe der Soll-Temperatur-Änderung
	    @rw_single_parameter,... 
	    '°C',  '%',   f_val,  f_sig, [],    [];...      
	'Power_Reduction',...      % Höhe der Leistungsreduktion
	    @rw_single_parameter,... 
	    '%',   '%',   f_val,  f_sig, [],    [];...      
	'Consider_non_stop_Parts',... % Berücksichtung der Non-Stop-Bereiche v. Lastkurve
	    @rw_single_parameter,... 
	    'bool','%',   f_val,  f_sig, [],    [];... 
	'Time_Postpone_Start',...  % Dauer der Einschaltverzögerung
	    @rw_single_parameter,... 
	    'min', '%',   f_val,  f_sig, [],    [];...  
	'Time_Postpone_max',...    % Maximale Dauer der Einschaltverzögerung
	    @rw_single_parameter,... 
	    'min', '%',   f_val,  f_sig, [],    [];... 
	};

%-------------------------------------------------------------------------------
% Auflistung der implementierten DSM-Funktionen:
%-------------------------------------------------------------------------------

Model.DSM_Input_Mode = {...			% DSM-Algorithmus:	
	'No_DSM_Function',...               % Keine DSM-Funktion
	'Frequency_Response_Simple',...	    % Frequenzschaltschwelle	
	'Frequency_Response_Priority',...   % Prioritätsgruppen               
	};
Model.DSM_Output_Mode = {...        % Reaktion des Gerätes:
	'No_DSM_Function',...               % Keine DSM-Funktion
	'Turn_Off',...					    % Ausschalten
	'Turn_Off_Stand_by',...			    % Verlassen des Stand-by-Modus
	'Change_Temp_Set',...			    % Soll-Temperatur-Änderung
	'Reduce_Input_Power',...		    % Leistungsreduktion
	'Postpone_Start',...			    % Verzögerung Einschalten
	'Pause_Programm',...                % Programm unterbrechen
	};
	
%===============================================================================
%              S I M U L A T I O N S E I N S T E L L U N G E N
%===============================================================================
%
% Startzeitpunkt der Simulation im Format TT-Mon-JJJJ HH:MM:SS
Model.Date_Start = '19-Feb-2010 00:00:00';
% Endzeitpunkt der Simulation im Format  TT-Mon-JJJJ HH:MM:SS
Model.Date_End =   '20-Feb-2010 00:00:00'; 

% Auflösung der Simulation: 'sec' = Sekundentakt
%                           '5se' = 5s Takt
%                           '10s' = 10s Takt
%                           'min' = Minutentakt
%                           '2.5m' = 2.5-Minutentakt (150s)
%                           '5mi' = 5-Minutentakt
%                           'quh' = Viertelstundentakt
%                           'hou' = Stundentakt
Model.Sim_Resolution = 'quh';

% Anzahl der Personen, deren durchschnittlicher Verbrauch simuliert werden soll. Wird hier
% der Wert 1 angegeben, wird von jedem zu simulierenden Gerätetyp ein aktives Gerät
% erzeugt und simuliert (siehe Abschnitt „2.2.1.3.1 Klasse Device“, Attribut Activity)  
Model.Number_User = 500;

Model.Use_DSM = false;       % Soll der DSM-Algorithmus laufen?
Model.Use_Same_DSM = false;% Sollen vorhandene DSM-Instanzen verwendet werden? 
                           %    (nur für Simulationsreihe relevant: Wert 'false'
                           %    bedeutet, das ungeachtet der anderen
                           %    Einstellungen neue DSM-Instanzen erzeugt
                           %    werden!)

% ------------------------------------------------------------------------------
%                   Gerätezusammenstellung und Einsatz:
% ------------------------------------------------------------------------------
for i=1:size(Model.Device_Assembly_Pool,1)
	% alle Möglichkeiten aktiv setzen:
	Model.Device_Assembly.(Model.Device_Assembly_Pool{i,1}) = 1; 
end
for i=1:size(Model.Devices_Pool,1)
	% alle Geräte aktiv setzen:
	Model.Device_Assembly_Simulation.(Model.Devices_Pool{i,1}) = 1; 
end
%===============================================================================
% Model-Struktur aktualisieren:
handles.Model = Model;