function handles = get_default_values(handles)
%GET_DEFAULT_VALUES    laden der Default-Werte für Simulationsprogramm
%    HANDLES = GET_DEFAULT_VALUES(HANDLES) fügt der HANDLES-Struktur des GUI
%    'Simulation' alle wichtigen Default-Werte und Definitionen hinzu. Falls
%    keine anderen Programmeinstellungen (z.B. von einem früheren
%    Simultionsdurchlauf) vorhanden sind, werden diese Werte herangezogen.

%    Franz Zeilinger - 02.02.2011 - R2008b lauffähig

%===============================================================================
%                  D E F A U L T - D E F I N I T I O N E N
%===============================================================================
%
%-------------------------------------------------------------------------------
% Einstellungen zur Programmkonfiguration (Datei-Verwaltung, Optionen):
%-------------------------------------------------------------------------------
% Speicherort für erzeugte Daten / Konfigurationseinstellungen:
Save = handles.Configuration.Save;
Save.Settings.Name = 'Einstellungen';
Save.Settings.Ext = '.conf';
% Ergebnisse und zusätzliche Daten werden im übergeordneten Verzeichnis
% abgelegt. Dieses muss zuvor ermittelt werden:
ind = strfind(Save.Settings.Path,'\');
Save.Additional_Data.Path = Save.Settings.Path(1:ind(end-1));
Save.Data.Main_Path = [Save.Additional_Data.Path,'Simulationsergebnisse\'];
% Default-Parameterwerte sollten hier abgelegt sein:
Save.Source.Path = Save.Settings.Path;
Save.Source.Parameter_Name = 'Default_Parameterwerte';
% Parameter für Joblistendatei (Multiple Simulationen):
Save.Joblist.Path = Save.Additional_Data.Path;
Save.Joblist.Parameter_Name = Save.Source.Parameter_Name;
Save.Joblist.List_Name = 'Simulationsreihe';
Save.Frequency.Path = Save.Additional_Data.Path;
Save.Frequency.Name = 'Frequenzdaten';
Save.Frequency.Extension = '.fqd';

opt.show_data = 1; %Daten nach Simulation anzeigen
opt.savas_xls = 0; %Daten als .xls nach Sim. speichern
opt.use_last_frequency_data = 0; %Aktuelle Frequenzdaten heranziehen
opt.use_different_frequency_data = 0; % Verwendung von verschiedenen Frequenzdaten
opt.use_same_paramter_file = 0;
opt.multiple_simulation = 0; %Modus auf Einzelsimualtion
opt.simsettings_load_from_paramfile = 0;   %Daten von Parameterdatei laden
opt.simsettings_load_from_main_window = 1; %Einstellungen von Hauptfenster
opt.use_same_devices = 0; %Wenn möglich, gleiche Geräteinstanzen verwenden
opt.use_same_dsm = 0; % Wenn möglich, gleiche DSM-Instanzen verwenden

Configuration.Save = Save;
Configuration.Options = opt; 
handles.Configuration = Configuration;

%===============================================================================
%               P A R A M E T E R D E F I N I T I O N E N :
%===============================================================================
%
%-------------------------------------------------------------------------------
% Möglichkeiten für zu simulierende Geräte(gruppen): Cell_Array für  
% automatisches Abarbeiten:
% { Variablenname, ausgeschriebener Name, Handle auf zuständige Klasse}
%-------------------------------------------------------------------------------
Model.Elements_Pool = {...
	'office', 'Bürogeräte',           @Probable_Operation;...
	'gr_avd', 'Gruppe "Audio-Video-Geräte"',   @Probable_Operation;...
% 	'tv_set', 'Fernseher',            @Probable_Operation;...
% 	'set_to', 'Set-Top-Boxen',        @Probable_Operation;...
% 	'vid_eq', 'Video-Equipment',      @Probable_Operation;...
% 	'gam_co', 'Game-Konsolen',        @Probable_Operation;...
% 	'hi_fi_', 'Hi-Fi-Geräte',         @Probable_Operation;...
% 	'radio_', 'Radios',               @Probable_Operation;...
% 	'illumi', 'Beleuchtung',          @Probable_Operation;...
	'refrig', 'Kühlschränke',         @Thermal_Storage;...
	'freeze', 'Gefriergeräte',        @Thermal_Storage;...
	'washer', 'Waschmaschinen',       @Loadcurve_Operation;...
	'dishwa', 'Geschirrspüler',       @Loadcurve_Operation;...
	'cl_dry', 'Wäschetrockner',       @Loadcurve_Operation;...
% 	'cookin', 'Kochen & Backen',      @Probable_Operation;...
% 	'war_wa', 'Warmwasser',           @Probable_Operation;...
% 	'cir_pu', 'Umwälzpumpe',          @Probable_Operation;...
% 	'miscel', 'Diverses',             @Probable_Operation;...
	}; 

%-------------------------------------------------------------------------------
% ACHTUNG: folgende Listen definieren die möglichen Namen für die verschiedenen,
% in diesem Programm vorkommenden Parameter. Werden diese Namen hier geändert,
% müssen die korrespondieren Properties in den Geräteklassen (bzw. bei den
% Simulationsparametern in den Programmfunktionen) dementsprechend geändert
% werden! Diese Definitionen dienen dazu, zukünftige weitere Parameter einfach
% ins Programm einfügen zu können, da deren Behandlung für Einlesen und Ausgabe
% mit Hilfe der rw_Funktinen automatisiert abläuft.
% Für nähere Infos siehe Hilfetext der verwendeten rw_-Funktionen (zu
% finden im Ordner 'Hilfsfunktionen' im Programmverzeichnis
%-------------------------------------------------------------------------------

% Auflistung aller möglichen Simulationsparameter:
%     {Parametername, Handle auf zuständige rw_-Funktion}
Model.Sim_Param_Pool = {...
	'Date_Start',     @rw_sim_parameter;...
	'Date_End',       @rw_sim_parameter;...
	'Sim_Resolution', @rw_sim_parameter;...
	'Number_User',    @rw_sim_parameter;
	'Use_DSM',        @rw_sim_parameter;...
	'Use_Same_DSM',   @rw_sim_parameter;...
	'Device_Assembly',@rw_dev_assembly;...
	};

f_val = '%6.1f'; %Formatstring für Parameterwerte
f_sig = '%4.1f'; %Formatstring für Varianzen u.d.gl.

% Auflistung möglicher Parametertypen der Geräte:
% {Parametername, ...
%      Handle auf zuständige rw_-Funktion,...
%      Argumtente f. rw_-Funtkion;}
% Nichtbnötigte Argumente werden (um Cell-Array zu ermöglichen) mit leeren
% Zellen ('[]') befüllt, damit jede Zeile die gleiche Spaltenanzahl hat!
Model.Parameter_Pool = {...
	'Power_Nominal',...          % Nennleistung
	    @rw_single_parameter,... 
	    'W',  '%',   f_val, f_sig, [],    [];...
	'Power_Stand_by',...         % Stand-by-Verbrauch
	    @rw_single_parameter,... 
	    'W',  '%',   f_val, f_sig, [],    [];...
	'Dir_therm_Flow',...         % Richtung der thermischen Energiezufuhr
		@rw_single_parameter,... 
	    '','n.n.', '%5.0f', f_sig, [],    [];...
	'Efficency',...              % Wirkungsgrad
	    @rw_single_parameter,... 
	    '%',  '%',   f_val, f_sig, [],    [];...      
	'Switch_Point',...           % Schaltschwelle
	    @rw_single_parameter,... 
	    '°C', '%',   f_val, f_sig, [],    [];...      
	'Heat_Capacity',...          % Wärmekapazität 
	    @rw_single_parameter,... 
	    'J/K','%',   f_val, f_sig, [],    [];...      
	'Thermal_Res',...            % thermischer Widerstand
	    @rw_single_parameter,... 
	    'K/W','%',   f_val, f_sig, [],    [];...      
	'Temp_Set',...               % Solltemperatur
	    @rw_single_parameter,... 
	    '°C', '%',   f_val, f_sig, [],    [];...      
	'Temp_Ambiance',...          % Umgebungstemperatur
	    @rw_single_parameter,... 
	    '°C', '%',   f_val, f_sig, [],    [];...      
	'Operat_Sim_Start',...       % Wahrschl. für Betrieb bei Simulationsstart
	    @rw_single_parameter,... 
	    '%',  'n.n.',f_val, f_sig, [],    [];...      
	'Time_Period',...            % Periodendauer 
	    @rw_single_parameter,... 
	    'min','%',   f_val, f_sig, [],    [];...      
	'Time_typ_Run',...           % typ. Laufzeit
	    @rw_parameter_list,... 
	    'min','%',   f_val, f_sig,'%5.1f','%5.1f';... 
	'Time_Start',...             % Startzeit
	    @rw_parameter_list,... 
	    'Uhr','min', '%s',  f_sig, '%s' , '%5.1f';...
	'Start_Probability',...      % Einschaltwahrscheinlichkeit
	    @rw_parameter_list,... 
	    '%',  'n.n.',f_val, f_sig,'%5.1f','%5.1f';... 
	'Power_Loadcurve',...        % Lastkurve
	    @rw_loadcurve,...                 
	    [],   [],    [],    [],    [],    [];...    
	'Loadcurve_Allocation',... % Einschaltwahrscheinlichkeit der versch. Lastkurven
	    @rw_parameter_list,...
	    '%',  'n.n.',f_val, f_sig,'%5.1f','%5.1f';... 
	'Loadcurve_non_stop_Parts',... % Definition der zusammenhängenden Teil der Lastk.
	    @rw_loadcurve_parts,...
	    [],   [],    [],    [],    [],    [];...
		};

% Auflistung möglicher Parametertype für DSM:
Model.DSM_Param_Pool = {...
	'DSM_Input_Mode',...       % Auswahl des zu verwendenden DSM-Algorithmus
	    @rw_dsm_modus,... 
	    [],    [],    [],     [],    [],    [];...      
	'Check_former_Frequ_Data',... % Überprüfung zurückliegender Frequenzdaten
	    @rw_single_parameter,... 
	    'bool','n.n.',[],     [],    [],    [];...      
	'DSM_Output_Mode',...      % Aúswahl der Reaktion des Gerätes
	    @rw_dsm_modus,... 
	    [],    [],    [],     [],    [],    [];...      
	'Frequency_Level',...      % Frequenzwert, ab dem DSM eingreift
	    @rw_single_parameter,... 
	    'Hz',  '%',   f_val,  f_sig, [],    [];...    
	'Frequency_Hysteresis',... % Frequenzwert der Breite der Hysterese der Frequenz 
	    @rw_single_parameter,... 
	    'Hz',  '%',   f_val,  f_sig, [],    [];...  
	'Frequ_Filter_Time',...    % Filterzeitkonstante für Frequenzfilterung
	    @rw_single_parameter,... 
	    'min', '%',   f_val,  f_sig, [],    [];...  	
	'Prioritys_Number',...     % Anzahl an Prioritätsgruppen von Verbrauchern
	    @rw_single_parameter,... 
	    '',    'n.n.','%6.0f',f_sig, [],    [];...      
	'Prioritys_Freq_Range',... % Frequenzbereich der einzelnen Prioritätsgruppen
	    @rw_parameter_list,... 
	    'Hz',  '%',   f_val,  f_sig,'%5.1f','%5.1f';... 
	'Prioritys_Allocation',... % Verteilung der Verbr. auf die Prioritätsgruppen
	    @rw_parameter_list,... 
	    '%',   'n.n.',f_val,  f_sig,'%5.1f','%5.1f';... 
	'Time_Delay_Restore_Op',...% Zeitverzögerung Wiederinbetriebnahme
	    @rw_single_parameter,... 
	    'min', '%',   f_val,  f_sig, [],    [];...  	
	'Temp_Set_Variation',...   % Höhe der Soll-Temperatur-Änderung
	    @rw_single_parameter,... 
	    '°C',  '%',   f_val,  f_sig, [],    [];...      
	'Power_Reduction',...      % Höhe der Leistungsreduktion
	    @rw_single_parameter,... 
	    '%',   '%',   f_val,  f_sig, [],    [];...      
	'Consider_non_stop_Parts',... % Berücksichtung der Non-Stop-Bereiche v. Lastkurve
	    @rw_single_parameter,... 
	    'bool','%',   f_val,  f_sig, [],    [];... 
	'Time_Postpone_Start',...  % Dauer der Einschaltverzögerung
	    @rw_single_parameter,... 
	    'min', '%',   f_val,  f_sig, [],    [];...  
	'Time_Postpone_max',...    % Maximale Dauer der Einschaltverzögerung
	    @rw_single_parameter,... 
	    'min', '%',   f_val,  f_sig, [],    [];... 
	};

%-------------------------------------------------------------------------------
% Auflistung der implementierten DSM-Funktionen:
%-------------------------------------------------------------------------------

Model.DSM_Input_Mode = {...			% DSM-Algorithmus:	
	'No_DSM_Function',...               % Keine DSM-Funktion
	'Frequency_Response_Simple',...	    % Frequenzschaltschwelle	
	'Frequency_Response_Priority',...   % Prioritätsgruppen               
	};
Model.DSM_Output_Mode = {...        % Reaktion des Gerätes:
	'No_DSM_Function',...               % Keine DSM-Funktion
	'Turn_Off',...					    % Ausschalten
	'Turn_Off_Stand_by',...			    % Verlassen des Stand-by-Modus
	'Change_Temp_Set',...			    % Soll-Temperatur-Änderung
	'Reduce_Input_Power',...		    % Leistungsreduktion
	'Postpone_Start',...			    % Verzögerung Einschalten
	'Pause_Programm',...                % Programm unterbrechen
	};
	
%===============================================================================
%              S I M U L A T I O N S E I N S T E L L U N G E N
%===============================================================================
%
% Startzeitpunkt TT-Mon-JJJJ HH:MM:SS
Model.Date_Start = '19-Feb-2010 00:00:00';
% Endzeitpunkt   TT-Mon-JJJJ HH:MM:SS
Model.Date_End =   '20-Feb-2010 00:00:00'; 

% Auflösung der Simulation: 'sec' = Sekundentakt
%                           'min' = Minutentakt
%                           '5mi' = 5-Minutentakt
%                           'quh' = Viertelstundendtakt
%                           'hou' = Stundentakt
Model.Sim_Resolution = 'hou';
Model.Number_User = 50;     % Anzahl der Personen, die die Geräte verwenden
Model.Use_DSM = true;       % Soll der DSM-Algorithmus laufen?
Model.Use_Same_DSM = true; % Sollen vorhandene DSM-Instanzen verwendet werden? 
                           %    (nur für Simulationsreihe relevant: Wert 'false'
                           %    bedeutet, das ungeachtet der anderen
                           %    Einstellungen neue DSM-Instanzen erzeugt
                           %    werden!)

% ------------------------------------------------------------------------------
%                   Gerätezusammenstellung und Einsatz:
% ------------------------------------------------------------------------------
for i=1:size(Model.Elements_Pool,1)
	% alle Geräte aktiv setzen:
	Model.Device_Assembly.(Model.Elements_Pool{i,1}) = 1; 
end
%===============================================================================
% Model-Struktur aktualisieren:
handles.Model = Model;