function Households = load_household_parameter(Path, Name, Model) %#ok<INUSL>
%LOAD_HOUSEHOLD_PARAMETER   Kurzbeschreibung fehlt.
%    Ausführliche Beschreibung fehlt!

% Franz Zeilinger - 14.09.2011

% { Variablenname, minimale Anzahl Personen, maximale Anzahl Personen, Genaue
% Bezeichnung };
Households.Types = Model.Households;

% Anzahl der Haushalte:
for i = 1:size(Households.Types,1)
	Households.Number.(Households.Types{i,1}) = Households.Types{i,5};
end

% { Gerätename, Ausstattung in %, Standardabweichung der Ausstattung in % vom 
%   Mittelwert, maximale Anzahl an Geräten }
Households.Device_Distribution.sing_vt = {...
	'Kühlschränke',   100.0, 30, 2;...
	'Gefriergeräte',   36.4, 30, 2;...
	'Geschirrspüler',  64.2, 30, 2;...
	'Waschmaschinen',  86.6, 30, 2;...
	'Wäschetrockner',  14.9, 30, 2;...
	'Fernseher',      118.0, 30, 3;...
	'Desktop PCs',     89.8, 30, 3;...
	};
Households.Device_Distribution.coup_vt = {...
	'Kühlschränke',   102.0, 30, 2;...
	'Gefriergeräte',   67.3, 30, 2;...
	'Geschirrspüler',  82.9, 30, 2;...
	'Waschmaschinen',  96.1, 30, 2;...
	'Wäschetrockner',  35.4, 30, 2;...
	'Fernseher',      169.0, 30, 3;...
	'Desktop PCs',    136.0, 30, 3;...
	};
Households.Device_Distribution.sing_pt = {...
	'Kühlschränke',    81.8, 30, 2;...
	'Gefriergeräte',   36.4, 30, 2;...
	'Geschirrspüler',  39.4, 30, 2;...
	'Waschmaschinen',  78.8, 30, 2;...
	'Wäschetrockner',  12.1, 30, 2;...
	'Fernseher',       90.9, 30, 3;...
	'Desktop PCs',     84.8, 30, 3;...
	};
Households.Device_Distribution.coup_pt = {...
	'Kühlschränke',   109.0, 30, 2;...
	'Gefriergeräte',   90.9, 30, 2;...
	'Geschirrspüler',  72.7, 30, 2;...
	'Waschmaschinen',  90.9, 30, 2;...
	'Wäschetrockner',  18.2, 30, 2;...
	'Fernseher',      182.0, 30, 3;...
	'Desktop PCs',    127.0, 30, 3;...
	};
Households.Device_Distribution.sing_rt = {...
	'Kühlschränke',    94.5, 30, 2;...
	'Gefriergeräte',   52.5, 30, 2;...
	'Geschirrspüler',  47.8, 30, 2;...
	'Waschmaschinen',  91.7, 30, 2;...
	'Wäschetrockner',  14.2, 30, 2;...
	'Fernseher',      133.0, 30, 3;...
	'Desktop PCs',     34.6, 30, 3;...
	};
Households.Device_Distribution.coup_rt = {...
	'Kühlschränke',   121.0, 30, 2;...
	'Gefriergeräte',  103.0, 30, 2;...
	'Geschirrspüler',  75.7, 30, 2;...
	'Waschmaschinen',  94.5, 30, 2;...
	'Wäschetrockner',  32.5, 30, 2;...
	'Fernseher',      182.0, 30, 3;...
	'Desktop PCs',     75.3, 30, 3;...
	};
Households.Device_Distribution.fami_2v = {...
	'Kühlschränke',   137.0, 30, 2;...
	'Gefriergeräte',  111.0, 30, 2;...
	'Geschirrspüler',  87.7, 30, 2;...
	'Waschmaschinen',  95.6, 30, 2;...
	'Wäschetrockner',  51.7, 30, 2;...
	'Fernseher',      253.0, 30, 3;...
	'Desktop PCs',    227.0, 30, 3;...
	};
Households.Device_Distribution.fami_1v = {...
	'Kühlschränke',   121.0, 30, 2;...
	'Gefriergeräte',   92.6, 30, 2;...
	'Geschirrspüler',  88.7, 30, 2;...
	'Waschmaschinen',  96.3, 30, 2;...
	'Wäschetrockner',  44.3, 30, 2;...
	'Fernseher',      189.0, 30, 3;...
	'Desktop PCs',    159.0, 30, 3;...
	};
Households.Device_Distribution.fami_rt = {...
	'Kühlschränke',   142.0, 30, 2;...
	'Gefriergeräte',  124.0, 30, 2;...
	'Geschirrspüler',  76.1, 30, 2;...
	'Waschmaschinen',  94.8, 30, 2;...
	'Wäschetrockner',  46.2, 30, 2;...
	'Fernseher',      249.0, 30, 3;...
	'Desktop PCs',    139.0, 30, 3;...
	};
% die oberen Listen anhand der bekannten Aufteilungen um weitere Geräte erweitern.
% Hier wird insbesondere mit dem Ausstattungsgrad von Fernsehern und Desktop PCs (die
% in der Statistik als Notebook + PCs angeführt sind) auf die Ausstattung mit den
% Zusatzgeräten geschlossen. Daten zu der Aufteiling: siehe DA Zeilinger 2010.
equ_degr_a_v = {...
	'Fernseher',           22.27;...
	'Set-Top-Boxen',       15.97;...
	'Video-Equipment',     17.23;...
	'Game-Konsolen',       14.71;...
	'Hi-Fi-Geräte',         9.24;...
	'Radios',              20.59;...
	};
equ_degr_office = {...
	'Desktop PCs',		   12.45;...
	'Notebooks',		   26.62;...
	'Monitore (PCs)',	   30.44;...	
	'Laserdrucker',		   17.51;...	
	'Tintenstrahldrucker', 23.21;...	
	'Diverse Bürogeräte',   2.18;...
	};

Known_Devices = {}; %leeres Ergebnis-Array
for k = 1:size(Households.Types,1)
	typ = Households.Types{k,1};
	% auslesen der bekannten Ausstattungsgrade:
	degr_tv_set = Households.Device_Distribution.(typ){6,2};
	degr_PC_NBs = Households.Device_Distribution.(typ){7,2};
	% Ausstattungsfaktor anhand der Ausstattung mit Fernsehgeräten bzw. PCs ermitteln:
	fact_av_dev = degr_tv_set / equ_degr_a_v{1,2};
	fact_office = degr_PC_NBs / (equ_degr_office{1,2} + equ_degr_office{2,2});
	% Nun die Geräte entsprechend anpassen, und der Haushaltsausstattung hinzufügen:
	Households.Device_Distribution.(typ)(end-1:end,:) = [];
	for i = 1:size(equ_degr_a_v,1)
		equ_degr_a_v{i,2} = equ_degr_a_v{i,2} * fact_av_dev;
		Households.Device_Distribution.(typ)(end+1,:) = ...
			{equ_degr_a_v{i,:}, 30, 3};
	end
	for i = 1:size(equ_degr_office,1)
		equ_degr_office{i,2} = equ_degr_office{i,2} * fact_office;
		Households.Device_Distribution.(typ)(end+1,:) = ...
			{equ_degr_office{i,:}, 30, 3};
	end
	
	% aus den angegebenen Geräten der Haushaltstypen die bekannten Gerätetypen
	% ermitteln:
	for i=1:size(Households.Device_Distribution.(typ),1)
		% Überprüfen, ob Array leer ist:
		if ~isempty(Known_Devices)
			% Falls nicht, überprüfen, ob es das Gerät bereits gibt:
			idx = find(strcmpi(Known_Devices(:,2),...
				Households.Device_Distribution.(typ)(i,1)), 1);
			if ~isempty(idx)
				% Falls ja, nächstes Gerät heranziehen:
				continue;
			end
		end
		% Falls Array leer, oder das Gerät noch nicht vorhanden, dieses zu den bekannten
		% Geräten hinzufügen:
		Known_Devices(end+1,:) = Model.Devices_Pool(strcmpi(...
			Model.Devices_Pool(:,2),Households.Device_Distribution.(typ)(i,1)),:); %#ok<AGROW>
	end
	
	% Die Ausstattung der Haushalte ermitteln:
	Number_Devices = zeros(size(Known_Devices,1),Households.Number.(typ));
	Number_Persons = zeros(1,Households.Number.(typ));
	for i=1:size(Households.Device_Distribution.(typ),1)
		% Index ermitteln, zu welchem bekannten Gerätetyp das aktuelle Gerät gehört, um
		% damit das Ergebnis-Array korrekt aufzubauen:
		name = Households.Device_Distribution.(typ){i,1};
		idx = strcmpi(Known_Devices(:,2),name);
		for j=1:Households.Number.(typ)
			% Ausstattung mit diesem Gerät:
			level_equ = Households.Device_Distribution.(typ){i,2}/100;
			% sichere Anzahl an Geräten (entspricht Anzahl an 100% in Ausstattung):
			sure_num_dev = floor(level_equ);
			% der Rest der Ausstattung (ohne sicher vorhandene Geräte):
			level_equ = level_equ - sure_num_dev;
			% Anzahl der weiteren Geräte ermitteln:
			num_dev = sure_num_dev + (rand() < level_equ);
			% Anzahl der Im Haushalt lebenden Personen ermitteln:
			idx_2 = find(strcmp(Households.Types(:,1),typ));
			min_per = Households.Types{idx_2,2};
			max_per = Households.Types{idx_2,3};
			if min_per >= max_per
				num_per = min_per;
			else
				num_per = min_per + round(rand()*(max_per - min_per));
			end
			Number_Persons(j) = num_per;
			% Mit der Anzahl an im Haushalt lebenden Personen multiplizieren (da
			% sämtliche Lastgänge definiert sind durch Geräteeinsatzwahrscheinlichkeit
			% pro Person, muss sich auch dies in der Anzahl der Geräte wiederspieglen -
			% So ist in einem Zwei-Personenhaushalt die Wahrscheinlichkeit für ein
			% aktives Geräte doppelt so hoch wie in einem Ein-Personenhaushalt. Durch die
			% doppelte Anzahl an Geräteerzeugungen wird der Geräteeinsatz doppelt
			% wahrscheinlich):
			num_dev = num_dev * num_per;
			% Im Ergebnis-Array speichern:
			Number_Devices(idx,j) = num_dev;
		end
	end
	% Ergebnisse in die Ausgabestruktur speichern:
	Households.Number_Devices.(typ) = Number_Devices;
	Households.Number_Dev_Tot.(typ) = sum(Number_Devices,2);
	Households.Number_Persons.(typ) = Number_Persons;
	Households.Number_Per_Tot.(typ) = sum(Number_Persons);
end
Households.Known_Devices_Pool = Known_Devices;
end

