function Households = load_household_parameter(~, ~, Model) 
%LOAD_HOUSEHOLD_PARAMETER   Kurzbeschreibung fehlt.
%    HOUSEHOLDS = LOAD_HOUSEHOLD_PARAMETER(PATH, NAME, MODEL)
%    Funtion ist vorbereitet, über die Parameter PATH und NAME auf eine Datei
%    zugreifen zu können, aus der die Konfiguration der Haushalte geladen werden
%    kann. Muss aber noch bei Bedarf implementiert werden!
%    Ausführliche Beschreibung fehlt!

% Erstellt von:            Franz Zeilinger - 14.09.2011
% Letzte Änderung durch:   Franz Zeilinger - 08.03.2013

% { Variablenname, minimale Anzahl Personen, maximale Anzahl Personen, Genaue
% Bezeichnung };
Households.Types = Model.Households;

% Anzahl der Haushalte:
for i = 1:size(Households.Types,1)
	Households.Statistics.(Households.Types{i,1}).Number = Households.Types{i,5};
end

% { Gerätename, Ausstattung in %, Standardabweichung der Ausstattung in % vom 
%   Mittelwert, maximale Anzahl an Geräten }
Households.Devices.home_1.Distribution = {...
	'Kühlschränke',     105.8, 30, 3;...
	'Gefriergeräte',     59.9, 30, 3;...
	'Waschmaschinen',    91.2, 30, 2;...
	'Wäschetrockner',    11.8, 30, 2;...
	'Geschirrspüler',    49.6, 30, 2;...
	'Fernseher',        161.8, 30, 3;...
	'Desktop PCs',       48.2, 30, 3;...
% 	'Wärmepumpe'         75.0, 20, 1;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',        12.5, 30, 2;...
% 	'Umwälzpumpen',     100.0, 20, 2;...
	'Umwälzpumpen',      69.2, 30, 2;...
% 	'Warmwasserboiler',  75.0, 20, 3;...
	'Warmwasserboiler',  29.2, 30, 3;...
	'Durchlauferhitzer',  8.3, 30, 1;...
	};
Households.Devices.home_2.Distribution = {...
	'Kühlschränke',     157.8, 30, 3;...
	'Gefriergeräte',     97.4, 30, 3;...
	'Waschmaschinen',    93.8, 30, 3;...
	'Wäschetrockner',    35.8, 30, 3;...
	'Geschirrspüler',    80.7, 30, 3;...
	'Fernseher',        200.1, 30, 4;...
	'Desktop PCs',       84.9, 30, 3;...
% 	'Wärmepumpe'         75.0, 20, 1;...
	'Wärmepumpe'          5.1, 30, 1;...
	'Heizkörper',         2.6, 30, 2;...
% 	'Umwälzpumpen',     100.0, 20, 2;...
	'Umwälzpumpen',      85.7, 30, 2;...
% 	'Warmwasserboiler',  75.0, 20, 3;...
	'Warmwasserboiler',  22.2, 30, 3;...
	'Durchlauferhitzer',  2.8, 30, 1;...
	};
Households.Devices.home_3.Distribution = {...
	'Kühlschränke',     183.4, 30, 4;...
	'Gefriergeräte',    111.2, 30, 3;...
	'Waschmaschinen',    92.3, 30, 3;...
	'Wäschetrockner',    42.4, 30, 3;...
	'Geschirrspüler',    81.4, 30, 3;...
	'Fernseher',        282.1, 30, 5;...
	'Desktop PCs',      161.6, 30, 4;...
% 	'Wärmepumpe'         75.0, 20, 1;...
	'Wärmepumpe'          4.8, 30, 1;...
	'Heizkörper',        14.3, 30, 2;...
% 	'Umwälzpumpen',     100.0, 20, 2;...
	'Umwälzpumpen',      72.0, 30, 2;...
% 	'Warmwasserboiler',  75.0, 20, 3;...
	'Warmwasserboiler',  43.5, 30, 3;...
	'Durchlauferhitzer',  4.3, 30, 1;...
	};
Households.Devices.hom_4p.Distribution = {...
	'Kühlschränke',     186.7, 30, 4;...
	'Gefriergeräte',    119.8, 30, 3;...
	'Waschmaschinen',    91.3, 30, 3;...
	'Wäschetrockner',    44.1, 30, 3;...
	'Geschirrspüler',    86.8, 30, 3;...
	'Fernseher',        262.3, 30, 5;...
	'Desktop PCs',      212.7, 30, 5;...
% 	'Wärmepumpe'         75.0, 20, 1;...
	'Wärmepumpe'          9.3, 30, 1;...
	'Heizkörper',         4.7, 30, 2;...
% 	'Umwälzpumpen',     100.0, 20, 2;...
	'Umwälzpumpen',      85.1, 30, 2;...
% 	'Warmwasserboiler',  75.0, 20, 3;...
	'Warmwasserboiler',  30.0, 30, 3;...
	'Durchlauferhitzer',  3.3, 30, 1;...
	};
Households.Devices.flat_1.Distribution = {...
	'Kühlschränke',     108.6, 30, 3;...
	'Gefriergeräte',     26.3, 30, 2;...
	'Waschmaschinen',    82.5, 30, 2;...
	'Wäschetrockner',     9.0, 30, 2;...
	'Geschirrspüler',    50.3, 30, 2;...
	'Fernseher',        112.4, 30, 3;...
	'Desktop PCs',       70.0, 30, 3;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',        13.2, 30, 2;...
	'Umwälzpumpen',      19.6, 30, 2;...
	'Warmwasserboiler',  45.8, 30, 3;...
	'Durchlauferhitzer',  8.3, 30, 1;...
	};
Households.Devices.flat_2.Distribution = {...
	'Kühlschränke',     124.8, 30, 3;...
	'Gefriergeräte',     53.7, 30, 3;...
	'Waschmaschinen',    86.2, 30, 3;...
	'Wäschetrockner',    12.5, 30, 3;...
	'Geschirrspüler',    69.3, 30, 3;...
	'Fernseher',        155.4, 30, 4;...
	'Desktop PCs',      116.5, 30, 3;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',         8.1, 30, 2;...
	'Umwälzpumpen',      39.5, 30, 2;...
	'Warmwasserboiler',  41.2, 30, 3;...
	'Durchlauferhitzer',  2.9, 30, 1;...
	};
Households.Devices.flat_3.Distribution = {...
	'Kühlschränke',     123.1, 30, 4;...
	'Gefriergeräte',     47.8, 30, 3;...
	'Waschmaschinen',    90.5, 30, 3;...
	'Wäschetrockner',    19.8, 30, 3;...
	'Geschirrspüler',    77.7, 30, 3;...
	'Fernseher',        188.2, 30, 5;...
	'Desktop PCs',      176.5, 30, 4;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',         0.0, 30, 2;...
	'Umwälzpumpen',      37.5, 30, 2;...
	'Warmwasserboiler',  43.8, 30, 3;...
	'Durchlauferhitzer',  0.0, 30, 1;...
	};
Households.Devices.fla_4p.Distribution = {...
	'Kühlschränke',     135.3, 30, 4;...
	'Gefriergeräte',     56.4, 30, 3;...
	'Waschmaschinen',    86.9, 30, 3;...
	'Wäschetrockner',    26.5, 30, 3;...
	'Geschirrspüler',    76.9, 30, 3;...
	'Fernseher',        206.2, 30, 5;...
	'Desktop PCs',      206.0, 30, 5;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',         0.0, 30, 2;...
	'Umwälzpumpen',      21.4, 30, 2;...
	'Warmwasserboiler',  66.7, 30, 3;...
	'Durchlauferhitzer',  6.7, 30, 1;...
	};

% --- Ausstattung für EDLEM ---
Households.Devices.sing_vt.Distribution = {...
	'Kühlschränke',     100.0, 30, 2;...
	'Gefriergeräte',     36.4, 30, 2;...
	'Geschirrspüler',    64.2, 30, 2;...
	'Waschmaschinen',    86.6, 30, 2;...
	'Wäschetrockner',    14.9, 30, 2;...
	'Fernseher',        118.0, 30, 3;...
	'Desktop PCs',       89.8, 30, 3;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',        12.5, 30, 2;...
	'Umwälzpumpen',      69.2, 30, 2;...
	'Warmwasserboiler',  29.2, 30, 3;...
	'Durchlauferhitzer',  8.3, 30, 1;...
	};
Households.Devices.coup_vt.Distribution = {...
	'Kühlschränke',     102.0, 30, 2;...
	'Gefriergeräte',     67.3, 30, 2;...
	'Geschirrspüler',    82.9, 30, 2;...
	'Waschmaschinen',    96.1, 30, 2;...
	'Wäschetrockner',    35.4, 30, 2;...
	'Fernseher',        169.0, 30, 3;...
	'Desktop PCs',      136.0, 30, 3;...
	'Wärmepumpe'          5.1, 30, 1;...
	'Heizkörper',         2.6, 30, 2;...
	'Umwälzpumpen',      85.7, 30, 2;...
	'Warmwasserboiler',  22.2, 30, 3;...
	'Durchlauferhitzer',  2.8, 30, 1;...
	};
Households.Devices.sing_pt.Distribution = {...
	'Kühlschränke',      81.8, 30, 2;...
	'Gefriergeräte',     36.4, 30, 2;...
	'Geschirrspüler',    39.4, 30, 2;...
	'Waschmaschinen',    78.8, 30, 2;...
	'Wäschetrockner',    12.1, 30, 2;...
	'Fernseher',         90.9, 30, 3;...
	'Desktop PCs',       84.8, 30, 3;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',        13.2, 30, 2;...
	'Umwälzpumpen',      19.6, 30, 2;...
	'Warmwasserboiler',  45.8, 30, 3;...
	'Durchlauferhitzer',  8.3, 30, 1;...
	};
Households.Devices.coup_pt.Distribution = {...
	'Kühlschränke',     109.0, 30, 2;...
	'Gefriergeräte',     90.9, 30, 2;...
	'Geschirrspüler',    72.7, 30, 2;...
	'Waschmaschinen',    90.9, 30, 2;...
	'Wäschetrockner',    18.2, 30, 2;...
	'Fernseher',        182.0, 30, 3;...
	'Desktop PCs',      127.0, 30, 3;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',         8.1, 30, 2;...
	'Umwälzpumpen',      39.5, 30, 2;...
	'Warmwasserboiler',  41.2, 30, 3;...
	'Durchlauferhitzer',  2.9, 30, 1;...
	};
Households.Devices.sing_rt.Distribution = {...
	'Kühlschränke',      94.5, 30, 2;...
	'Gefriergeräte',     52.5, 30, 2;...
	'Geschirrspüler',    47.8, 30, 2;...
	'Waschmaschinen',    91.7, 30, 2;...
	'Wäschetrockner',    14.2, 30, 2;...
	'Fernseher',        133.0, 30, 3;...
	'Desktop PCs',       34.6, 30, 3;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',        13.2, 30, 2;...
	'Umwälzpumpen',      19.6, 30, 2;...
	'Warmwasserboiler',  45.8, 30, 3;...
	'Durchlauferhitzer',  8.3, 30, 1;...
	};
Households.Devices.coup_rt.Distribution = {...
	'Kühlschränke',     121.0, 30, 2;...
	'Gefriergeräte',    103.0, 30, 2;...
	'Geschirrspüler',    75.7, 30, 2;...
	'Waschmaschinen',    94.5, 30, 2;...
	'Wäschetrockner',    32.5, 30, 2;...
	'Fernseher',        182.0, 30, 3;...
	'Desktop PCs',       75.3, 30, 3;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',         8.1, 30, 2;...
	'Umwälzpumpen',      39.5, 30, 2;...
	'Warmwasserboiler',  41.2, 30, 3;...
	'Durchlauferhitzer',  2.9, 30, 1;...
	};
Households.Devices.fami_2v.Distribution = {...
	'Kühlschränke',     137.0, 30, 2;...
	'Gefriergeräte',    111.0, 30, 2;...
	'Geschirrspüler',    87.7, 30, 2;...
	'Waschmaschinen',    95.6, 30, 2;...
	'Wäschetrockner',    51.7, 30, 2;...
	'Fernseher',        253.0, 30, 3;...
	'Desktop PCs',      227.0, 30, 3;...
	'Wärmepumpe'          4.8, 30, 1;...
	'Heizkörper',        14.3, 30, 2;...
	'Umwälzpumpen',      72.0, 30, 2;...
	'Warmwasserboiler',  43.5, 30, 3;...
	'Durchlauferhitzer',  4.3, 30, 1;...
	};
Households.Devices.fami_1v.Distribution = {...
	'Kühlschränke',     121.0, 30, 2;...
	'Gefriergeräte',     92.6, 30, 2;...
	'Geschirrspüler',    88.7, 30, 2;...
	'Waschmaschinen',    96.3, 30, 2;...
	'Wäschetrockner',    44.3, 30, 2;...
	'Fernseher',        189.0, 30, 3;...
	'Desktop PCs',      159.0, 30, 3;...
	'Wärmepumpe'          0.0, 30, 1;...
	'Heizkörper',         0.0, 30, 2;...
	'Umwälzpumpen',      37.5, 30, 2;...
	'Warmwasserboiler',  43.8, 30, 3;...
	'Durchlauferhitzer',  0.0, 30, 1;...
	};
Households.Devices.fami_rt.Distribution = {...
	'Kühlschränke',     142.0, 30, 2;...
	'Gefriergeräte',    124.0, 30, 2;...
	'Geschirrspüler',    76.1, 30, 2;...
	'Waschmaschinen',    94.8, 30, 2;...
	'Wäschetrockner',    46.2, 30, 2;...
	'Fernseher',        249.0, 30, 3;...
	'Desktop PCs',      139.0, 30, 3;...
	'Wärmepumpe'          9.3, 30, 1;...
	'Heizkörper',         4.7, 30, 2;...
	'Umwälzpumpen',      85.1, 30, 2;...
	'Warmwasserboiler',  30.0, 30, 3;...
	'Durchlauferhitzer',  3.3, 30, 1;...
	};
% die oberen Listen anhand der bekannten Aufteilungen um weitere Geräte erweitern.
% Hier wird insbesondere mit dem Ausstattungsgrad von Fernsehern und Desktop PCs (die
% in der Statistik als Notebook + PCs angeführt sind) auf die Ausstattung mit den
% Zusatzgeräten geschlossen. Daten zu der Aufteiling: siehe DA Zeilinger 2010.
equ_degr_a_v = {...
	'Fernseher',           22.27;...
	'Set-Top-Boxen',       15.97;...
	'Video-Equipment',     17.23;...
	'Game-Konsolen',       14.71;...
	'Hi-Fi-Geräte',         9.24;...
	'Radios',              20.59;...
	};
equ_degr_office = {...
	'Desktop PCs',		   12.45;...
	'Notebooks',		   26.62;...
	'Monitore (PCs)',	   30.44;...	
	'Laserdrucker',		   17.51;...	
	'Tintenstrahldrucker', 23.21;...	
	'Diverse Bürogeräte',   2.18;...
	};

Known_Devices = {}; %leeres Ergebnis-Array
for k = 1:size(Households.Types,1)
	typ = Households.Types{k,1};
	% wo befinden sich die Angaben für Fernseher?
	idx_tv_set = strcmpi(Households.Devices.(typ).Distribution(:,1),'fernseher');
	% auslesen der bekannten Ausstattungsgrade für Fernseher + sonstige
	% Einstellungen: 
	degr_tv_set = Households.Devices.(typ).Distribution(idx_tv_set,2:end);
	% Löschen der entsprechenden Zeile:
	Households.Devices.(typ).Distribution(idx_tv_set,:) = [];
	% Das gleiche für die PCs + Notebooks:
	idx_pc_des = strcmpi(Households.Devices.(typ).Distribution(:,1),'desktop pcs');
	degr_PC_NBs = Households.Devices.(typ).Distribution(idx_pc_des,2:end);
	Households.Devices.(typ).Distribution(idx_pc_des,:) = [];
	% Ausstattungsfaktor anhand der Ausstattung mit Fernsehgeräten bzw. PCs+Notebooks
	% ermitteln: 
	fact_av_dev = degr_tv_set{1} / equ_degr_a_v{1,2};
	fact_office = degr_PC_NBs{1} / equ_degr_office{1,2};
	% Nun die Geräte entsprechend anpassen, und der Haushaltsausstattung hinzufügen:
	for i = 1:size(equ_degr_a_v,1)
		equ_degr_a_v{i,2} = equ_degr_a_v{i,2} * fact_av_dev;
		Households.Devices.(typ).Distribution(end+1,:) = ...
			{equ_degr_a_v{i,:}, degr_tv_set{2}, degr_tv_set{3}}; 
	end
	for i = 1:size(equ_degr_office,1)
		equ_degr_office{i,2} = equ_degr_office{i,2} * fact_office;
		Households.Devices.(typ).Distribution(end+1,:) = ...
			{equ_degr_office{i,:}, degr_PC_NBs{2}, degr_PC_NBs{3}};
	end
	
	% aus den angegebenen Geräten der Haushaltstypen die bekannten Gerätetypen
	% ermitteln:
	for i=1:size(Households.Devices.(typ).Distribution,1)
		% Überprüfen, ob Array leer ist:
		if ~isempty(Known_Devices)
			% Falls nicht, überprüfen, ob es das Gerät bereits gibt:
			idx = find(strcmpi(Known_Devices(:,2),...
				Households.Devices.(typ).Distribution(i,1)), 1);
			if ~isempty(idx)
				% Falls ja, nächstes Gerät heranziehen:
				continue;
			end
		end
		% Falls Array leer, oder das Gerät noch nicht vorhanden, dieses zu den bekannten
		% Geräten hinzufügen:
		Known_Devices(end+1,:) = Model.Devices_Pool(strcmpi(...
			Model.Devices_Pool(:,2),Households.Devices.(typ).Distribution(i,1)),:); %#ok<AGROW>
	end
	
	% Die Ausstattung der Haushalte ermitteln:
	Number_Devices = zeros(size(Known_Devices,1),Households.Statistics.(typ).Number);
	Number_Persons = zeros(1,Households.Statistics.(typ).Number);
	for i=1:size(Households.Devices.(typ).Distribution,1)
		% Index ermitteln, zu welchem bekannten Gerätetyp das aktuelle Gerät gehört,
		% um damit das Ergebnis-Array korrekt aufzubauen:
		name = Households.Devices.(typ).Distribution{i,1};
		idx = strcmpi(Known_Devices(:,2),name);
		for j=1:Households.Statistics.(typ).Number
			% Ausstattung mit diesem Gerät:
			level_equ = Households.Devices.(typ).Distribution{i,2}/100;
			% sichere Anzahl an Geräten (entspricht Anzahl an 100% in Ausstattung):
			sure_num_dev = floor(level_equ);
			% der Rest der Ausstattung (ohne sicher vorhandene Geräte):
			level_equ = level_equ - sure_num_dev;
			% Anzahl der weiteren Geräte ermitteln:
			num_dev = sure_num_dev + (rand() < level_equ);
			% Anzahl der Im Haushalt lebenden Personen ermitteln:
			idx_2 = find(strcmp(Households.Types(:,1),typ));
			min_per = Households.Types{idx_2,2};
			max_per = Households.Types{idx_2,3};
			if min_per >= max_per
				num_per = min_per;
			else
				num_per = min_per + round(rand()*(max_per - min_per));
			end
			Number_Persons(j) = num_per;
			% Im Ergebnis-Array speichern:
			Number_Devices(idx,j) = num_dev;
		end
	end
	% Ergebnisse in die Ausgabestruktur speichern:
	Households.Devices.(typ).Number_Known = Number_Devices;
	Households.Devices.(typ).Number_Known_Tot = sum(Number_Devices,2);
	Households.Statistics.(typ).Number_Persons = Number_Persons;
	Households.Statistics.(typ).Number_Per_Tot = sum(Number_Persons);
end
Households.Devices.Pool_Known = Known_Devices;
end

